[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
estudos = "GvgrvreWmPmCM1YhBAL8q3CUG3b4WDueZFzbFMyHqs6L"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/junior/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
